### PR TITLE
fix README JS SDK charts

### PR DESCRIPTION
**Pull request by im-calvin**
small fix from the README. Let me know if it should be something else / y'all have plans to update it in the future

### CODE REVIEW

**Review by mlejva — APPROVED** [review]

**Comment by im-calvin** [comment]
I can't seem to get the image out from the result. But looking at this makes me think that the README should actually say `result.data[0].png`, not `result.data[0]['image/png']`. Any advice here? 

image

**Comment by mlejva** [comment]
Ah, sorry yes. The JS SDK isn't completely up to date to the Python version. 

> I can't seem to get the image out from the result.

How does the code you sent to `execCell()` looks like in this example?

**Comment by im-calvin** [comment]
Sorry I was being stupid it was a problem on my end. Anyways, yeah the README should say `data[0].png` :)

**Comment by mlejva** [comment]
I'll update the readme. It might actually be this in the near future 😅
```js
const execution = await codeInterpreter.notebook.execCell(...)
execution.results[0].png
```

**Comment by im-calvin** [comment]
Yeah no worries, I figured it seemed a little too similar to the Python version

**Pull request merged**
